### ISSUE TITLE
logs not indexed on MacOS

### ISSUE THREAD

**Issue by makuk66** [lvthillo/docker-elk#1]
Thanks @lvthillo for this repo and the associated article on [ITNEXT](https://itnext.io/deploy-elk-stack-in-docker-to-monitor-containers-c647d7e2bfcd).

If you're using Docker Desktop for Mac, the config provided does not work — the logs do not make it to Logstash or ElasticSearch. Per [the Docker docs](https://docs.docker.com/docker-for-mac/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host) you need:

```
    logging:
      driver: gelf
      options:
        gelf-address: "udp://host.docker.internal:12201"
```
in the [docker-compose.yml](https://github.com/lvthillo/docker-elk/blob/master/docker-compose.yml#L41), and similarly:

```
docker run -d -p 8080:80 --log-driver gelf --log-opt gelf-address=udp://host.docker.internal:12201 nginx:latest
```

when running Nginx.

I just figured I'd mention that here in case it might save someone else some time.
